#! /bin/sh

bspc monitor -d web dev dir txt vid pad mus gfx dis obs

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

# bspc config focused_border_color	"#29d7e2"
# bspc config normal_border_color		"#3C3C3C"
bspc config presel_feedback_color "#1a1a1a"
bspc config active_border_color		"#4fc3f7"
bspc config focused_border_color "#4fc3f7"
bspc config normal_border_color "#1a1a1a"

# bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 1280x720+0+0 center=true
bspc rule -a qimgv state=floating
bspc rule -a sxiv state=floating
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a mpv state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a kitty state=floating layer=normal sticky=on 
bspc rule -a 'GitHub Desktop' desktop='^2' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a obs desktop='^10' follow=on
bspc rule -a discord desktop='^9' follow=on

# start up stuff
xsetroot -cursor_name left_ptr &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst &
picom --animations -b &
feh --bg-fill ~/.config/backgrounds/wallhaven-m3w6pk_3440x1440.png &

## Polybar or tint
~/.config/bspwm/polybar-bspwm &

## Clipmemu start
# clipmenud &

## apps for systray if enabled
# volumeicon &
# nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
fi
