#!/usr/bin/env bash
Deskname=$(bspc query -D -d focused --names)
if [ "$Deskname" = "web" ]; then
	notify-send -t 3500 "Workspace 1  |  web"
elif [ "$Deskname" = "dev" ]; then
	notify-send -t 3500 "Workspace 2  |  dev"
elif [ "$Deskname" = "dir" ]; then
	notify-send -t 3500 "Workspace 3  |  dir"
elif [ "$Deskname" = "txt" ]; then
	notify-send -t 3500 "Workspace 4  |  txt"
elif [ "$Deskname" = "vid" ]; then
	notify-send -t 3500 "Workspace 5  |  vid"
elif [ "$Deskname" = "pad" ]; then
	notify-send -t 3500 "Workspace 6  |  pad"
elif [ "$Deskname" = "mus" ]; then
	notify-send -t 3500 "Workspace 7  |  mus"
elif [ "$Deskname" = "gfx" ]; then
	notify-send -t 3500 "Workspace 8  |  gfx"
elif [ "$Deskname" = "dis" ]; then
	notify-send -t 3500 "Workspace 9  |  dis"
elif [ "$Deskname" = "obs" ]; then
	notify-send -t 3500 "Workspace 10  |  obs"
else
	notify-send -t 3500 "$Deskname"
fi
